# distributed training
nodes: 1
gpus: 2
nr: 0
dataparallel: 0
workers: 8
visible_gpus: "4,7"

# Paths
data_root: "/home/wqzhao/Documents/Max/tiles_512_10x_FiveClass_IdentifyTumor"
train_csv: "./train_identifyTumor.csv"
valid_csv: "./valid_identifyTumor.csv"
checkpoints: "./checkpoints"
task: "IdentifyTumor"

# Model options
encoder: "efficientnet-b0"
weights: "imagenet"
act: "softmax"


# training options
batch_size: 16
epochs: 50

# optimizer options
lr: 0.0001
