# distributed training
nodes: 1
gpus: 4
nr: 0
dataparallel: 0
workers: 8
visible_gpus: "0,1,2,3"

# Paths
data_root: "/home/r20user17/Documents/tiles_512_10x_FiveClass_IdentifyTumor"
train_csv: "./train_IdentifyTumor.csv"
valid_csv: "./valid_IdentifyTumor.csv"
checkpoints: "./checkpoints"
task: "IdentifyTumor"


# Model options
encoder: "efficientnet-b1"
decoder: "Unet"
weights: "imagenet"
act: "softmax"


# training options
batch_size: 22
epochs: 50

# optimizer options
lr: 0.0001
